function help names changed
mpeg5/xeve pull request #113
Opened 2024-05-28 16:02 UTC by Jamaika1

2024-06-04 09:09 UTC, dariusz-f requested changes
This change is not universal and will cause problems on small terminal windows.

2024-06-04 09:26 UTC, dkozinski commented
It is worth considering listing the allowed values ​​of the xeve_app option one after the other.
The disadvantage of this solution is that the help printout will be "very long" (there are some options, such as the transfer option with 19 allowed values). Still, the undoubted advantage is that it will always be well formatted, regardless of the terminal used.

2024-09-21 05:44 UTC, kpchoi reviewed
It is possible that this PR could make mis-leading of EVC spec.
for example, 'unspecified' is different from 'unknown'.
I'd like to suggest this PR could be raised again with more investigation.
Regarding re-formatting of help message, needs why line break is required.

2025-07-16 10:21 UTC, kpchoi commented
This PR could not be merged to main branch because of lack of concensus.

2025-07-16 10:21 UTC, closed without merging