Add CodingStandards.md file
mpeg5/xeve pull request #143
Opened 2024-09-04 10:54 UTC by dkozinski

- Created a new file containing coding standards and best practices for the project
- Outlined guidelines to ensure code quality and consistency among team members

2024-09-04 11:07 UTC, dariusz-f requested changes, later dismissed

2024-09-04 11:07 UTC, dariusz-f commented on doc/CodingStandards.md
> +/ This is a single-line comment
missing /

2024-09-13 09:26 UTC, kpchoi approved these changes
Great explanation for coding style of this project!

2025-07-16 10:24 UTC, kpchoi approved these changes
LGTM

2025-07-16 10:26 UTC, merged