Changes in CMakeLists.txt files needed to build a project for Windows…
mpeg5/xeve pull request #59
Opened 2022-06-14 12:24 UTC by dkozinski

… in the MinGW environment using the MSVC compiler

2022-06-14 15:36 UTC, dariusz-f requested changes

2022-06-14 15:36 UTC, dariusz-f commented on CMakeLists.txt
> +
In my opinion it will be better to place this guide on project wiki page, not here.

2022-06-14 15:36 UTC, dariusz-f commented on CMakeLists.txt
>  elseif( UNIX OR MINGW )
Is this if else is necessary in this situation when windows code is commented out?

2022-06-15 10:12 UTC, dariusz-f approved these changes
looks good

2022-06-19 23:10 UTC, kpchoi approved these changes
LGTM

2022-06-19 23:11 UTC, merged