gop32 configuration support in xeve main profile
mpeg5/xeve pull request #91
Opened 2023-02-06 08:49 UTC by mamthan

2023-02-07 09:48 UTC, dariusz-f requested changes

2023-02-07 09:48 UTC, dariusz-f commented on src_base/xeve_def.h
> +#define XEVE_MAX_NUM_RPLS                       64
Duplicated definition. In heve.h should be enough, so you can remove define from this file.

2023-02-07 09:48 UTC, dariusz-f commented on inc/xeve.h
> +    /* max num of RPL is 64 after gop32 support */
Remove "after gop32 support" this info is superfluous.

2023-02-08 07:36 UTC, dariusz-f approved these changes
looks good

2023-02-09 10:06 UTC, mss-park approved these changes
Looks good to me.

2023-02-13 07:23 UTC, merged